services:
  twinkle-server-1:
    image: gong-fastapi-backend:latest
    container_name: gong-fastapi-backend-1
    restart: always
    volumes:
      - /opt/rod-browser-cache:/root/.cache/rod/browser
    networks:
      - edge
    ports:
     - "9099:9099"

networks:
  edge:
    external: true
